// <auto-generated />
using System;
using AgentGroupChat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentGroupChat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613003602_PartyInviteSchema")]
    partial class PartyInviteSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AgentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppearanceSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompactionBudget")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHumanParticipant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporarilySuspended")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTokensOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpawnedByAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspendedByAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuspendedUntilRound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseLongTermMemoryStorage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseShortTermMemoryStorage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AiConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiConnections");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AiModelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiModels");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideSetupGuide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KokoroBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KokoroLangCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KokoroModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("KokoroSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("KokoroUserVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KokoroVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PiperExePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PiperModelsDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SetupModelsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SetupRoomsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetupTtsStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TtsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TtsRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UiAccent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UiTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.DataTrackerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("PrivilegedAgentPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "DataKey")
                        .IsUnique()
                        .HasFilter("\"AgentId\" IS NULL");

                    b.HasIndex("RoomId", "AgentId", "DataKey")
                        .IsUnique()
                        .HasFilter("\"AgentId\" IS NOT NULL");

                    b.ToTable("DataTracking");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.ImageConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("ImageConnections");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.ImageModelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("GuidanceScale")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("ImageModels");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.LogEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("RoomId");

                    b.HasIndex("Source");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.MemoryBlockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "AgentId", "Kind")
                        .IsUnique();

                    b.ToTable("MemoryBlocks");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.PromptSampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPromptSampleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsBuiltIn");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("PromptSamples");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.RoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurableMemoryPromptSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNpcSpawning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePrivilegedActions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSceneArchive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSceneImageGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxArchivedScenes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentNpcs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemoryModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NpcBaseInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcCompactionBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NpcDefaultFemaleVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NpcDefaultMaleVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NpcMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NpcModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcPromptSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PauseAfterEveryReply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivilegedAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecentTurnsWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SceneImageModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneImageNegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneImageStyleNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedRoomMemoryPromptSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StoreDurableMemory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StoreLongTermArchives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StoreSharedRoomMemory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummarizationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SummarizerBroaderTurns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SummarizerMaxCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SummarizerMaxLines")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SummarizerMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummarizerModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummarizerPromptOverride")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("TtsEnabledOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsFallbackVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsProviderOverride")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsUserVoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCreativeImageGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSummarizer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCompactionBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WaitForUserReply")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.RoomInviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedeemedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RedeemedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomInvites");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.SceneArchiveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurableSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMajor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyEntities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedRoomSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId", "RoundNumber");

                    b.ToTable("SceneArchives");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.TranscriptTurnEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("TranscriptTurns");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AgentEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany("Agents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AiConnectionEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AiModelEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.AppSettingsEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.DataTrackerEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany("DataTrackers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.ImageConnectionEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.ImageModelEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.LogEntryEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.MemoryBlockEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.PromptSampleEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.RoomEntity", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.SceneArchiveEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.TranscriptTurnEntity", b =>
                {
                    b.HasOne("AgentGroupChat.Infrastructure.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentGroupChat.Infrastructure.Entities.RoomEntity", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("DataTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
